#ifndef FOCUSWIDGET_GLOBAL_H
#define FOCUSWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FOCUSWIDGET_LIBRARY)
#  define FOCUSWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FOCUSWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FOCUSWIDGET_GLOBAL_H
